using System;
using System.Windows;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Media.Animation;
using RTS_Tactical_Overlay.Native;

namespace RTS_Tactical_Overlay.Views;

/// <summary>
/// Transparent window for edge glow breathing effect
/// Two instances: one for left edge, one for right edge
/// </summary>
public partial class SideGlowWindow : Window
{
    // ============== 字段定义 ==============
    // 这些变量存储窗口运行时的状态

    /// <summary>
    /// Which edge this window belongs to
    /// true = left edge, false = right edge
    /// </summary>
    private readonly bool _isLeftEdge;

    /// <summary>
    /// Current glow color (RGB values)
    /// </summary>
    private Color _currentGlowColor;

    /// <summary>
    /// User-configured maximum brightness (0.1 - 1.0)
    /// </summary>
    private double _maxIntensity;

    /// <summary>
    /// User-configured breathing cycle duration in seconds
    /// </summary>
    private double _breathSpeedSeconds;

    /// <summary>
    /// WPF animation container (controls the timeline)
    /// </summary>
    private Storyboard? _breathingStoryboard;

    /// <summary>
    /// The actual opacity animation
    /// </summary>
    private DoubleAnimation? _breathingAnimation;

    /// <summary>
    /// Whether animation is currently running
    /// </summary>
    private bool _isAnimating;

    // ============== 构造函数 ==============

    /// <summary>
    /// Creates a SideGlowWindow for specified edge
    /// </summary>
    public SideGlowWindow(bool isLeftEdge)
    {
        // InitializeComponent() is auto-generated by WPF
        // It loads the XAML file and creates all UI elements
        InitializeComponent();

        _isLeftEdge = isLeftEdge;

        // Position window at correct edge of screen
        PositionWindow();

        // Setup gradient direction (left vs right have opposite gradients)
        SetupGradientDirection();
    }

    // ============== 窗口定位 ==============

    /// <summary>
    /// Positions the window at the screen edge
    /// </summary>
    private void PositionWindow()
    {
        // Top = 0 means start from top of screen
        Top = 0;

        // Height = full screen height (cover entire edge)
        Height = SystemParameters.PrimaryScreenHeight;

        if (_isLeftEdge)
        {
            // Left edge window: position at x = 0 (leftmost)
            Left = 0;
        }
        else
        {
            // Right edge window: position at (screen width - window width)
            // This places it at the rightmost edge
            Left = SystemParameters.PrimaryScreenWidth - Width;
        }
    }

    /// <summary>
    /// Sets the gradient direction based on edge position
    /// </summary>
    private void SetupGradientDirection()
    {
        if (_isLeftEdge)
        {
            // Left edge: glow starts bright at left, fades to transparent at right
            // Offset 0 = left side (bright)
            ColorStop.Offset = 0;
            // Offset 1 = right side (transparent)
            TransparentStop.Offset = 1;
        }
        else
        {
            // Right edge: glow starts transparent at left, bright at right
            // Offset 0 = left side (transparent)
            ColorStop.Offset = 1;
            // Offset 1 = right side (bright)
            TransparentStop.Offset = 0;
        }
    }

    // ============== Windows API 调用 ==============

    /// <summary>
    /// Called after window handle is created
    /// We apply WS_EX_NOACTIVATE here to prevent focus stealing
    /// </summary>
    protected override void OnSourceInitialized(EventArgs e)
    {
        base.OnSourceInitialized(e);

        // Get the window handle (HWND) - a unique ID Windows uses to identify windows
        var hwnd = new WindowInteropHelper(this).Handle;

        // Read current extended window style flags
        var extendedStyle = Win32Methods.GetWindowLong(hwnd, Win32Constants.GWL_EXSTYLE);

        // Add WS_EX_NOACTIVATE: tells Windows "this window should never get focus"
        // Add WS_EX_TOOLWINDOW: hides window from Alt+Tab switcher
        Win32Methods.SetWindowLong(hwnd, Win32Constants.GWL_EXSTYLE,
            extendedStyle | Win32Constants.WS_EX_NOACTIVATE | Win32Constants.WS_EX_TOOLWINDOW);
    }

    // ============== 公共方法 ==============

    /// <summary>
    /// Sets the glow width and repositions if right edge
    /// </summary>
    public void SetWidth(double width)
    {
        Width = width;

        if (!_isLeftEdge)
        {
            // Right edge window needs repositioning after width change
            // Otherwise it would move away from the edge
            Left = SystemParameters.PrimaryScreenWidth - width;
        }
    }

    /// <summary>
    /// Starts the breathing animation
    /// </summary>
    public void StartBreathing(Color color, double breathSpeedSeconds, double maxIntensity)
    {
        // Store parameters for later use
        _currentGlowColor = color;
        _breathSpeedSeconds = breathSpeedSeconds;
        _maxIntensity = maxIntensity;

        // Set initial brightness (start at 30% to avoid sudden flash)
        UpdateGradientColor(0.3);

        // Create animation storyboard
        CreateBreathingAnimation();

        // Begin the animation
        _breathingStoryboard?.Begin();
        _isAnimating = true;
    }

    /// <summary>
    /// Updates glow color instantly without restarting animation
    /// </summary>
    public void UpdateColor(Color color)
    {
        _currentGlowColor = color;

        // Use the border's current opacity (animation sets this value)
        double currentOpacity = GlowBorder.Opacity;

        // Apply new color at the same brightness level
        UpdateGradientColor(currentOpacity);
    }

    /// <summary>
    /// Pauses breathing at current brightness
    /// </summary>
    public void PauseBreathing()
    {
        if (_isAnimating && _breathingStoryboard != null)
        {
            _breathingStoryboard.Pause();
        }
    }

    /// <summary>
    /// Resumes breathing from paused brightness
    /// </summary>
    public void ResumeBreathing()
    {
        if (_isAnimating && _breathingStoryboard != null)
        {
            _breathingStoryboard.Resume();
        }
    }

    /// <summary>
    /// Stops breathing and fades out smoothly
    /// </summary>
    public void StopBreathing()
    {
        // Remove rendering event handler to prevent memory leak
        CompositionTarget.Rendering -= OnRendering;

        // Stop the looping animation
        if (_breathingStoryboard != null)
        {
            _breathingStoryboard.Stop();
            _isAnimating = false;
        }

        // Create a fade-out animation (0.3 seconds)
        var fadeOutAnimation = new DoubleAnimation
        {
            From = GlowBorder.Opacity,      // Start from current brightness
            To = 0,                          // End at 0 (fully transparent)
            Duration = TimeSpan.FromSeconds(0.3),
            FillBehavior = FillBehavior.Stop // Don't hold final value
        };

        // When fade completes, ensure gradient is fully transparent
        fadeOutAnimation.Completed += (s, e) =>
        {
            UpdateGradientColor(0);
            GlowBorder.Opacity = 0;
        };

        // Apply fade animation to the GlowBorder
        GlowBorder.BeginAnimation(OpacityProperty, fadeOutAnimation);
    }

    // ============== 内部方法 ==============

    /// <summary>
    /// Updates the gradient color with specified opacity
    /// </summary>
    private void UpdateGradientColor(double opacity)
    {
        // Calculate final opacity: multiply by maxIntensity to respect user's brightness limit
        double finalOpacity = opacity * _maxIntensity;

        // Convert to alpha byte (0-255)
        byte alpha = (byte)(finalOpacity * 255);

        // Create color with alpha channel
        // Alpha controls transparency: 0 = invisible, 255 = fully visible
        Color colorWithAlpha = Color.FromArgb(alpha, _currentGlowColor.R, _currentGlowColor.G, _currentGlowColor.B);

        // Apply to the gradient stop (this updates the visual immediately)
        ColorStop.Color = colorWithAlpha;
    }

    /// <summary>
    /// Creates the breathing animation storyboard
    /// </summary>
    private void CreateBreathingAnimation()
    {
        // Stop any existing animation first
        _breathingStoryboard?.Stop();

        // Create opacity animation: 0.1 → 1.0 → 0.1 → 1.0 ...
        _breathingAnimation = new DoubleAnimation
        {
            From = 0.1,                       // Minimum brightness
            To = 1.0,                         // Maximum brightness
            Duration = TimeSpan.FromSeconds(_breathSpeedSeconds / 2), // Half cycle (up only)
            AutoReverse = true,               // Automatically go back down (creates full cycle)
            RepeatBehavior = RepeatBehavior.Forever, // Loop indefinitely
            FillBehavior = FillBehavior.Stop  // Don't hold final value when stopped
        };

        // Create storyboard (container for animations)
        _breathingStoryboard = new Storyboard();
        _breathingStoryboard.Children.Add(_breathingAnimation);

        // Tell storyboard which element to animate
        Storyboard.SetTarget(_breathingAnimation, GlowBorder);
        // Tell storyboard which property to animate
        Storyboard.SetTargetProperty(_breathingAnimation, new PropertyPath(OpacityProperty));

        // Use CompositionTarget.Rendering to sync color with opacity each frame
        // This event fires before each frame is rendered
        CompositionTarget.Rendering -= OnRendering;
        CompositionTarget.Rendering += OnRendering;
    }

    /// <summary>
    /// Called each frame before rendering
    /// Updates gradient color to match current opacity
    /// </summary>
    private void OnRendering(object? sender, EventArgs e)
    {
        if (_isAnimating)
        {
            // Read the current opacity (animation sets this value)
            double currentOpacity = GlowBorder.Opacity;
            UpdateGradientColor(currentOpacity);
        }
    }
}